<a href="https://colab.research.google.com/github/vivekworldwide/Deep-learning-Notes/blob/main/pytorch_rnn_based_qa_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df = pd.read_csv('/content/100_Unique_QA_Dataset.csv')

df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [3]:
# tokenize
def tokenize(text):
  text=text.lower()
  text = text.replace('?', '')
  text = text.replace("'", "")
  return text.split()

In [4]:
tokenize("'Who wrote 'To Kill a Mockingbird'?'")

['who', 'wrote', 'to', 'kill', 'a', 'mockingbird']

In [5]:
# vocab
vocab = {'<UNK>':0}

In [6]:
def build_vocab(row):
  tokenized_question= tokenize(row['question'])
  tokenized_answer = tokenize(row['answer'])
  merged_tokens = tokenized_question+tokenized_answer
  print(merged_tokens)

  for token in merged_tokens:

    if token not in vocab:
      vocab[token]= len(vocab)

In [7]:
df.apply(build_vocab, axis= 1)

['what', 'is', 'the', 'capital', 'of', 'france', 'paris']
['what', 'is', 'the', 'capital', 'of', 'germany', 'berlin']
['who', 'wrote', 'to', 'kill', 'a', 'mockingbird', 'harper-lee']
['what', 'is', 'the', 'largest', 'planet', 'in', 'our', 'solar', 'system', 'jupiter']
['what', 'is', 'the', 'boiling', 'point', 'of', 'water', 'in', 'celsius', '100']
['who', 'painted', 'the', 'mona', 'lisa', 'leonardo-da-vinci']
['what', 'is', 'the', 'square', 'root', 'of', '64', '8']
['what', 'is', 'the', 'chemical', 'symbol', 'for', 'gold', 'au']
['which', 'year', 'did', 'world', 'war', 'ii', 'end', '1945']
['what', 'is', 'the', 'longest', 'river', 'in', 'the', 'world', 'nile']
['what', 'is', 'the', 'capital', 'of', 'japan', 'tokyo']
['who', 'developed', 'the', 'theory', 'of', 'relativity', 'albert-einstein']
['what', 'is', 'the', 'freezing', 'point', 'of', 'water', 'in', 'fahrenheit', '32']
['which', 'planet', 'is', 'known', 'as', 'the', 'red', 'planet', 'mars']
['who', 'is', 'the', 'author', 'of', '1984', 'george-orwell']
['what', 'is', 'the', 'currency', 'of', 'the', 'united', 'kingdom', 'pound']
['what', 'is', 'the', 'capital', 'of', 'india', 'delhi']
['who', 'discovered', 'gravity', 'newton']
['how', 'many', 'continents', 'are', 'there', 'on', 'earth', '7']
['which', 'gas', 'do', 'plants', 'use', 'for', 'photosynthesis', 'co2']
['what', 'is', 'the', 'smallest', 'prime', 'number', '2']
['who', 'invented', 'the', 'telephone', 'alexander-graham-bell']
['what', 'is', 'the', 'capital', 'of', 'australia', 'canberra']
['which', 'ocean', 'is', 'the', 'largest', 'pacific-ocean']
['what', 'is', 'the', 'speed', 'of', 'light', 'in', 'vacuum', '299,792,458m/s']
['which', 'language', 'is', 'spoken', 'in', 'brazil', 'portuguese']
['who', 'discovered', 'penicillin', 'alexander-fleming']
['what', 'is', 'the', 'capital', 'of', 'canada', 'ottawa']
['what', 'is', 'the', 'largest', 'mammal', 'on', 'earth', 'whale']
['which', 'element', 'has', 'the', 'atomic', 'number', '1', 'hydrogen']
['what', 'is', 'the', 'tallest', 'mountain', 'in', 'the', 'world', 'everest']
['which', 'city', 'is', 'known', 'as', 'the', 'big', 'apple', 'newyork']
['how', 'many', 'planets', 'are', 'in', 'the', 'solar', 'system', '8']
['who', 'painted', 'starry', 'night', 'vangogh']
['what', 'is', 'the', 'chemical', 'formula', 'of', 'water', 'h2o']
['what', 'is', 'the', 'capital', 'of', 'italy', 'rome']
['which', 'country', 'is', 'famous', 'for', 'sushi', 'japan']
['who', 'was', 'the', 'first', 'person', 'to', 'step', 'on', 'the', 'moon', 'armstrong']
['what', 'is', 'the', 'main', 'ingredient', 'in', 'guacamole', 'avocado']
['how', 'many', 'sides', 'does', 'a', 'hexagon', 'have', '6']
['what', 'is', 'the', 'currency', 'of', 'china', 'yuan']
['who', 'wrote', 'pride', 'and', 'prejudice', 'jane-austen']
['what', 'is', 'the', 'chemical', 'symbol', 'for', 'iron', 'fe']
['what', 'is', 'the', 'hardest', 'natural', 'substance', 'on', 'earth', 'diamond']
['which', 'continent', 'is', 'the', 'largest', 'by', 'area', 'asia']
['who', 'was', 'the', 'first', 'president', 'of', 'the', 'united', 'states', 'george-washington']
['which', 'bird', 'is', 'known', 'for', 'its', 'ability', 'to', 'mimic', 'sounds', 'parrot']
['what', 'is', 'the', 'longest-running', 'animated', 'tv', 'show', 'simpsons']
['what', 'is', 'the', 'smallest', 'country', 'in', 'the', 'world', 'vaticancity']
['which', 'planet', 'has', 'the', 'most', 'moons', 'saturn']
['who', 'wrote', 'romeo', 'and', 'juliet', 'shakespeare']
['what', 'is', 'the', 'main', 'gas', 'in', 'earths', 'atmosphere', 'nitrogen']
['how', 'many', 'bones', 'are', 'in', 'the', 'adult', 'human', 'body', '206']
['which', 'metal', 'is', 'a', 'liquid', 'at', 'room', 'temperature', 'mercury']
['what', 'is', 'the', 'capital', 'of', 'russia', 'moscow']
['who', 'discovered', 'electricity', 'benjamin-franklin']
['which', 'is', 'the', 'second-largest', 'country', 'by', 'land', 'area', 'canada']
['what', 'is', 'the', 'color', 'of', 'a', 'ripe', 'banana', 'yellow']
['which', 'month', 'has', '28', 'days', 'in', 'a', 'common', 'year', 'february']
['what', 'is', 'the', 'study', 'of', 'living', 'organisms', 'called', 'biology']
['which', 'country', 'is', 'home', 'to', 'the', 'great', 'wall', 'china']
['what', 'do', 'bees', 'collect', 'from', 'flowers', 'nectar']
['what', 'is', 'the', 'opposite', 'of', 'day', 'night']
['what', 'is', 'the', 'capital', 'of', 'south', 'korea', 'seoul']
['who', 'invented', 'the', 'light', 'bulb', 'edison']
['which', 'gas', 'do', 'humans', 'breathe', 'in', 'for', 'survival', 'oxygen']
['what', 'is', 'the', 'square', 'root', 'of', '144', '12']
['which', 'country', 'has', 'the', 'pyramids', 'of', 'giza', 'egypt']
['which', 'sea', 'creature', 'has', 'eight', 'arms', 'octopus']
['which', 'holiday', 'is', 'celebrated', 'on', 'december', '25', 'christmas']
['what', 'is', 'the', 'currency', 'of', 'japan', 'yen']
['how', 'many', 'legs', 'does', 'a', 'spider', 'have', '8']
['which', 'sport', 'uses', 'a', 'net,', 'ball,', 'and', 'hoop', 'basketball']
['which', 'country', 'is', 'famous', 'for', 'its', 'kangaroos', 'australia']
['who', 'was', 'the', 'first', 'female', 'prime', 'minister', 'of', 'the', 'uk', 'margaretthatcher']
['which', 'is', 'the', 'fastest', 'land', 'animal', 'cheetah']
['what', 'is', 'the', 'first', 'element', 'on', 'the', 'periodic', 'table', 'hydrogen']
['what', 'is', 'the', 'capital', 'of', 'spain', 'madrid']
['which', 'planet', 'is', 'the', 'closest', 'to', 'the', 'sun', 'mercury']
['who', 'is', 'known', 'as', 'the', 'father', 'of', 'computers', 'charlesbabbage']
['what', 'is', 'the', 'capital', 'of', 'mexico', 'mexicocity']
['how', 'many', 'colors', 'are', 'in', 'a', 'rainbow', '7']
['which', 'musical', 'instrument', 'has', 'black', 'and', 'white', 'keys', 'piano']
['who', 'discovered', 'the', 'americas', 'in', '1492', 'christophercolumbus']
['which', 'disney', 'character', 'has', 'a', 'long', 'nose', 'and', 'grows', 'it', 'when', 'lying', 'pinocchio']
['who', 'directed', 'the', 'movie', 'titanic', 'jamescameron']
['which', 'superhero', 'is', 'also', 'known', 'as', 'the', 'dark', 'knight', 'batman']
['what', 'is', 'the', 'capital', 'of', 'brazil', 'brasilia']
['which', 'fruit', 'is', 'known', 'as', 'the', 'king', 'of', 'fruits', 'mango']
['which', 'country', 'is', 'known', 'for', 'the', 'eiffel', 'tower', 'france']

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [8]:
len(vocab)

324

In [9]:
from torch import index_reduce
# convert words to numerical indices
def text_to_indices(text, vocab):

  indexed_text =[]

  for token in tokenize(text):
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])
  return indexed_text

In [10]:
text_to_indices("What is low value", vocab)

[1, 2, 0, 0]

In [11]:
import torch
from torch.utils.data import Dataset, DataLoader

In [12]:
class QADataset(Dataset):

  def __init__(self, df, vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self, index):
    numerical_question = text_to_indices(self.df.iloc[index]['question'], self.vocab)
    numerical_answer = text_to_indices(self.df.iloc[index]['answer'], self.vocab)

    return torch.tensor(numerical_question), torch.tensor(numerical_answer)

In [13]:
dataset = QADataset(df, vocab)

In [14]:
dataset[1]

(tensor([1, 2, 3, 4, 5, 8]), tensor([9]))

In [15]:

dataloader = DataLoader(dataset, batch_size=1, shuffle=True)

for question, answer in dataloader:
  print(question, answer)

tensor([[  1,   2,   3,  37,  38,  39, 161]]) tensor([[162]])
tensor([[ 10,  11, 157, 158, 159]]) tensor([[160]])
tensor([[ 78,  79, 261, 151,  14, 262, 153]]) tensor([[36]])
tensor([[  1,   2,   3, 141, 117,  83,   3, 277, 278]]) tensor([[121]])
tensor([[  1,   2,   3,   4,   5, 135]]) tensor([[136]])
tensor([[  1,   2,   3,  69,   5, 155]]) tensor([[156]])
tensor([[  1,   2,   3,  37, 133,   5,  26]]) tensor([[134]])
tensor([[10, 96,  3, 97]]) tensor([[98]])
tensor([[ 10, 308,   3, 309, 310]]) tensor([[311]])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([[49]])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([[16]])
tensor([[  1,   2,   3, 234,   5, 235]]) tensor([[131]])
tensor([[ 10,  75, 208]]) tensor([[209]])
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([[41]])
tensor([[  1,   2,   3, 146,  86,  19, 192, 193]]) tensor([[194]])
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]]) tensor([[72]])
tensor([[ 42, 137,   2, 138,  39, 175, 269]]) tensor([[99]])
tensor([[ 10,  96,   3, 104, 239]]) tensor([[240]])
tensor([[ 42, 216, 118, 217, 218,  19,  14, 219,  43]]) tensor([[220]])
tensor([[ 10, 140,   3, 141, 171,   5,   3,  70, 172]]) tensor([[173]])
tensor([[ 42,  18,   2,   3, 281,  12,   3, 282]]) tensor([[205]])
tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]]) tensor([[52]])
tensor([[ 78,  79, 150, 151,  14, 152, 153]]) tensor([[154]])
tensor([[10, 29,  3, 30, 31]]) tensor([[32]])
tensor([[ 42,   2,   3, 210, 137, 168, 211, 169]]) tensor([[113]])
tensor([[ 42, 255,   2, 256,  83, 257, 258]]) tensor([[259]])
tensor([[  1,   2,   3, 212,   5,  14, 213, 214]]) tensor([[215]])
tensor([[ 78,  79, 288,  81,  19,  14, 289]]) tensor([[85]])
tensor([[ 42, 263, 264,  14, 265, 266, 158, 267]]) tensor([[268]])
tensor([[  1,  87, 229, 230, 231, 232]]) tensor([[233]])
tensor([[  1,   2,   3,   4,   5, 236, 237]]) tensor([[238]])
tensor([[78, 79, 80, 81, 82, 83, 84]]) tensor([[85]])
tensor([[ 10,  75, 111]]) tensor([[112]])
tensor([[  1,   2,   3, 180, 181, 182, 183]]) tensor([[184]])
tensor([[ 1,  2,  3,  4,  5, 73]]) tensor([[74]])
tensor([[42, 18,  2, 62, 63,  3, 64, 18]]) tensor([[65]])
tensor([[10,  2,  3, 66,  5, 67]]) tensor([[68]])
tensor([[ 42, 200,   2,  14, 201, 202, 203, 204]]) tensor([[205]])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]) tensor([[124]])
tensor([[ 42, 107,   2, 108,  19, 109]]) tensor([[110]])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]) tensor([[61]])
tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]]) tensor([[36]])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]) tensor([[106]])
tensor([[  1,   2,   3,   4,   5, 113]]) tensor([[114]])
tensor([[ 10, 140,   3, 141, 270,  93, 271,   5,   3, 272]]) tensor([[273]])
tensor([[ 10,  11, 189, 158, 190]]) tensor([[191]])
tensor([[ 42, 167,   2,   3,  17, 168, 169]]) tensor([[170]])
tensor([[ 10,  75,   3, 296,  19, 297]]) tensor([[298]])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([[7]])
tensor([[  1,   2,   3,   4,   5, 206]]) tensor([[207]])
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]) tensor([[23]])
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([[54]])
tensor([[ 42,  86,  87, 241, 242,  19,  39, 243]]) tensor([[244]])
tensor([[10, 55,  3, 56,  5, 57]]) tensor([[58]])
tensor([[ 42, 101,   2,   3,  17]]) tensor([[102]])
tensor([[ 42,  18, 118,   3, 186, 187]]) tensor([[188]])
tensor([[  1,   2,   3,  17, 115,  83,  84]]) tensor([[116]])
tensor([[ 42, 318,   2,  62,  63,   3, 319,   5, 320]]) tensor([[321]])
tensor([[ 10,  29, 130, 131]]) tensor([[132]])
tensor([[ 42, 137,   2,  62,  39,   3, 322, 323]]) tensor([[6]])
tensor([[ 10,   2,  62,  63,   3, 283,   5, 284]]) tensor([[285]])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([[28]])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([[9]])
tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]]) tensor([[179]])
tensor([[ 42, 250, 251, 118, 252, 253]]) tensor([[254]])
tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]]) tensor([[199]])
tensor([[ 42, 137, 118,   3, 247,   5, 248]]) tensor([[249]])
tensor([[ 10, 140,   3, 141, 142,  12, 143,  83,   3, 144]]) tensor([[145]])
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]]) tensor([[128]])
tensor([[10, 75, 76]]) tensor([[77]])
tensor([[  1,   2,   3, 163, 164, 165,  83,  84]]) tensor([[166]])
tensor([[ 42,   2,   3, 274, 211, 275]]) tensor([[276]])
tensor([[ 42, 137,   2, 138,  39, 139]]) tensor([[53]])
tensor([[  1,   2,   3,  33,  34,   5, 245]]) tensor([[246]])
tensor([[ 42, 117, 118,   3, 119,  94, 120]]) tensor([[121]])
tensor([[  1,   2,   3,   4,   5, 109]]) tensor([[317]])
tensor([[  1,   2,   3,   4,   5, 286]]) tensor([[287]])
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]]) tensor([[185]])
tensor([[ 1,  2,  3, 33, 34,  5, 35]]) tensor([[36]])
tensor([[ 42, 137,   2, 226,  12,   3, 227, 228]]) tensor([[155]])
tensor([[ 1,  2,  3,  4,  5, 99]]) tensor([[100]])
tensor([[  1,   2,   3, 221,   5, 222, 223, 224]]) tensor([[225]])
tensor([[  1,   2,   3,   4,   5, 279]]) tensor([[280]])
tensor([[ 1,  2,  3, 92, 93, 94]]) tensor([[95]])
tensor([[ 1,  2,  3, 69,  5, 53]]) tensor([[260]])
tensor([[  1,   2,   3, 146, 147,  19, 148]]) tensor([[149]])
tensor([[ 42, 290, 291, 118, 292, 158, 293, 294]]) tensor([[295]])
tensor([[42, 86, 87, 88, 89, 39, 90]]) tensor([[91]])
tensor([[ 42, 312,   2, 313,  62,  63,   3, 314, 315]]) tensor([[316]])
tensor([[ 42, 299, 300, 118,  14, 301, 302, 158, 303, 304, 305, 306]]) tensor([[307]])

In [16]:
import torch.nn as nn

In [17]:
class SimpleRNN(nn.Module):

  def __init__ (self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
    self.rnn = nn.RNN(50,64, batch_first = True)
    self.fc = nn.Linear(64,vocab_size)

  def forward(self, question):
    embedded_question = self.embedding(question)
    hidden, final = self.rnn(embedded_question)
    output = self.fc(final.squeeze(0))

    return output

In [18]:
learning_rate = 0.001
epochs = 20

In [19]:
model = SimpleRNN(len(vocab))

In [20]:
criterian = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = learning_rate)

In [22]:
import torch.nn.functional as F
#training loop
for epoch in range(epochs):

  total_loss= 0
  for question, answer in dataloader:

    optimizer.zero_grad()

    #forward  pass
    output = model(question)

    #loss
    loss = criterian(output, answer.squeeze(-1))

    #gradient
    loss.backward()

    #weight update
    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch+1}, loss: {total_loss:.4f}")

Epoch: 1, loss: 523.5792
Epoch: 2, loss: 454.3348
Epoch: 3, loss: 372.5498
Epoch: 4, loss: 312.2115
Epoch: 5, loss: 261.2336
Epoch: 6, loss: 213.7459
Epoch: 7, loss: 169.6023
Epoch: 8, loss: 130.9747
Epoch: 9, loss: 100.3221
Epoch: 10, loss: 76.6127
Epoch: 11, loss: 58.6136
Epoch: 12, loss: 46.0733
Epoch: 13, loss: 36.2741
Epoch: 14, loss: 29.5734
Epoch: 15, loss: 24.3803
Epoch: 16, loss: 20.3005
Epoch: 17, loss: 17.0465
Epoch: 18, loss: 14.3969
Epoch: 19, loss: 12.3407
Epoch: 20, loss: 10.6409

In [ ]:
def predict(model, question, threshold=0.5):

  # convert question to numbers
  numerical_question = text_to_indices(question, vocab)

  # tensor
  question_tensor = torch.tensor(numerical_question).unsqueeze(0)

  # send to model
  output = model(question_tensor)

  # convert logits to probs
  probs = torch.nn.functional.softmax(output, dim=1)

  # find index of max prob
  value, index = torch.max(probs, dim=1)

  if value < threshold:
    print("I don't know")

  print(list(vocab.keys())[index])

In [ ]:
predict(model, "What is the largest planet in our solar system?")

In [ ]:
list(vocab.keys())[7]